// Code generated by "gcraft_stringer -type=ErrorType"; DO NOT EDIT.

package auth

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GruntSuccess-0]
	_ = x[GruntFailBanned-3]
	_ = x[GruntFailUnknownAccount-4]
	_ = x[GruntFailIncorrectPassword-5]
	_ = x[GruntFailAlreadyOnline-6]
	_ = x[GruntFailNoTime-7]
	_ = x[GruntFailDbBusy-8]
	_ = x[GruntFailVersionInvalid-9]
	_ = x[GruntFailVersionUpdate-10]
	_ = x[GruntFailInvalidServer-11]
	_ = x[GruntFailSuspended-12]
	_ = x[GruntFailFailNoaccess-13]
	_ = x[GruntSuccessSurvey-14]
	_ = x[GruntFailParentcontrol-15]
	_ = x[GruntFailLockedEnforced-16]
	_ = x[GruntFailTrialEnded-17]
	_ = x[GruntFailUseBattlenet-18]
	_ = x[GruntFailAntiIndulgence-19]
	_ = x[GruntFailExpired-20]
	_ = x[GruntFailNoGameAccount-21]
	_ = x[GruntFailChargeback-22]
	_ = x[GruntFailInternetGameRoomWithoutBnet-23]
	_ = x[GruntFailGameAccountLocked-24]
	_ = x[GruntFailUnlockableLock-25]
	_ = x[GruntFailConversionRequired-32]
	_ = x[GruntFailDisconnected-255]
}

const (
	_ErrorType_name_0 = "GruntSuccess"
	_ErrorType_name_1 = "GruntFailBannedGruntFailUnknownAccountGruntFailIncorrectPasswordGruntFailAlreadyOnlineGruntFailNoTimeGruntFailDbBusyGruntFailVersionInvalidGruntFailVersionUpdateGruntFailInvalidServerGruntFailSuspendedGruntFailFailNoaccessGruntSuccessSurveyGruntFailParentcontrolGruntFailLockedEnforcedGruntFailTrialEndedGruntFailUseBattlenetGruntFailAntiIndulgenceGruntFailExpiredGruntFailNoGameAccountGruntFailChargebackGruntFailInternetGameRoomWithoutBnetGruntFailGameAccountLockedGruntFailUnlockableLock"
	_ErrorType_name_2 = "GruntFailConversionRequired"
	_ErrorType_name_3 = "GruntFailDisconnected"
)

var (
	_ErrorType_index_1 = [...]uint16{0, 15, 38, 64, 86, 101, 116, 139, 161, 183, 201, 222, 240, 262, 285, 304, 325, 348, 364, 386, 405, 441, 467, 490}
)

func (i ErrorType) String() string {
	switch {
	case i == 0:
		return _ErrorType_name_0
	case 3 <= i && i <= 25:
		i -= 3
		return _ErrorType_name_1[_ErrorType_index_1[i]:_ErrorType_index_1[i+1]]
	case i == 32:
		return _ErrorType_name_2
	case i == 255:
		return _ErrorType_name_3
	default:
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
