// DO NOT EDIT: this file was auto-generated by Gophercraft/protoss

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: bgs/low/pb/client/user_manager_types.proto

package v1

import (
	protocol "github.com/Gophercraft/core/bnet/pb/bgs/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of bgs/low/pb/client/global_extensions/field_options.proto.

type LogOption = protocol.LogOption

const LogOption_HIDDEN = protocol.LogOption_HIDDEN
const LogOption_HEX = protocol.LogOption_HEX

var LogOption_name = protocol.LogOption_name
var LogOption_value = protocol.LogOption_value

type EntityIdRestriction_Kind = protocol.EntityIdRestriction_Kind

const EntityIdRestriction_ANY = protocol.EntityIdRestriction_ANY
const EntityIdRestriction_ACCOUNT = protocol.EntityIdRestriction_ACCOUNT
const EntityIdRestriction_GAME_ACCOUNT = protocol.EntityIdRestriction_GAME_ACCOUNT
const EntityIdRestriction_ACCOUNT_OR_GAME_ACCOUNT = protocol.EntityIdRestriction_ACCOUNT_OR_GAME_ACCOUNT
const EntityIdRestriction_SERVICE = protocol.EntityIdRestriction_SERVICE
const EntityIdRestriction_CHANNEL = protocol.EntityIdRestriction_CHANNEL

var EntityIdRestriction_Kind_name = protocol.EntityIdRestriction_Kind_name
var EntityIdRestriction_Kind_value = protocol.EntityIdRestriction_Kind_value

type BGSFieldOptions = protocol.BGSFieldOptions
type FieldRestriction = protocol.FieldRestriction
type FieldRestriction_Signed = protocol.FieldRestriction_Signed
type FieldRestriction_Unsigned = protocol.FieldRestriction_Unsigned
type FieldRestriction_Float = protocol.FieldRestriction_Float
type FieldRestriction_String_ = protocol.FieldRestriction_String_
type FieldRestriction_Repeated = protocol.FieldRestriction_Repeated
type FieldRestriction_Message = protocol.FieldRestriction_Message
type FieldRestriction_EntityId = protocol.FieldRestriction_EntityId
type FieldRestriction_Bytes = protocol.FieldRestriction_Bytes
type RepeatedFieldRestriction = protocol.RepeatedFieldRestriction
type RepeatedFieldRestriction_Signed = protocol.RepeatedFieldRestriction_Signed
type RepeatedFieldRestriction_Unsigned = protocol.RepeatedFieldRestriction_Unsigned
type RepeatedFieldRestriction_Float = protocol.RepeatedFieldRestriction_Float
type RepeatedFieldRestriction_String_ = protocol.RepeatedFieldRestriction_String_
type RepeatedFieldRestriction_EntityId = protocol.RepeatedFieldRestriction_EntityId
type RepeatedFieldRestriction_Bytes = protocol.RepeatedFieldRestriction_Bytes
type SignedFieldRestriction = protocol.SignedFieldRestriction
type UnsignedFieldRestriction = protocol.UnsignedFieldRestriction
type FloatFieldRestriction = protocol.FloatFieldRestriction
type StringFieldRestriction = protocol.StringFieldRestriction
type EntityIdRestriction = protocol.EntityIdRestriction
type MessageFieldRestriction = protocol.MessageFieldRestriction

var E_FieldOptions = protocol.E_FieldOptions
var E_Valid = protocol.E_Valid

type RecentPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId        *protocol.EntityId    `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Program         *string               `protobuf:"bytes,2,opt,name=program" json:"program,omitempty"`
	TimestampPlayed *uint64               `protobuf:"fixed64,3,opt,name=timestamp_played,json=timestampPlayed" json:"timestamp_played,omitempty"`
	Attributes      []*protocol.Attribute `protobuf:"bytes,4,rep,name=attributes" json:"attributes,omitempty"`
	Counter         *uint32               `protobuf:"fixed32,6,opt,name=counter,def=0" json:"counter,omitempty"`
}

// Default values for RecentPlayer fields.
const (
	Default_RecentPlayer_Counter = uint32(0)
)

func (x *RecentPlayer) Reset() {
	*x = RecentPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_user_manager_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecentPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentPlayer) ProtoMessage() {}

func (x *RecentPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_user_manager_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentPlayer.ProtoReflect.Descriptor instead.
func (*RecentPlayer) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_user_manager_types_proto_rawDescGZIP(), []int{0}
}

func (x *RecentPlayer) GetEntityId() *protocol.EntityId {
	if x != nil {
		return x.EntityId
	}
	return nil
}

func (x *RecentPlayer) GetProgram() string {
	if x != nil && x.Program != nil {
		return *x.Program
	}
	return ""
}

func (x *RecentPlayer) GetTimestampPlayed() uint64 {
	if x != nil && x.TimestampPlayed != nil {
		return *x.TimestampPlayed
	}
	return 0
}

func (x *RecentPlayer) GetAttributes() []*protocol.Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *RecentPlayer) GetCounter() uint32 {
	if x != nil && x.Counter != nil {
		return *x.Counter
	}
	return Default_RecentPlayer_Counter
}

type BlockedPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId *protocol.EntityId `protobuf:"bytes,1,req,name=account_id,json=accountId" json:"account_id,omitempty"`
	BattleTag *string            `protobuf:"bytes,2,opt,name=battle_tag,json=battleTag" json:"battle_tag,omitempty"`
	// Deprecated: Marked as deprecated in bgs/low/pb/client/user_manager_types.proto.
	Role []uint32 `protobuf:"varint,3,rep,name=role" json:"role,omitempty"`
	// Deprecated: Marked as deprecated in bgs/low/pb/client/user_manager_types.proto.
	Privileges *uint64 `protobuf:"varint,4,opt,name=privileges" json:"privileges,omitempty"`
}

func (x *BlockedPlayer) Reset() {
	*x = BlockedPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_user_manager_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockedPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockedPlayer) ProtoMessage() {}

func (x *BlockedPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_user_manager_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockedPlayer.ProtoReflect.Descriptor instead.
func (*BlockedPlayer) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_user_manager_types_proto_rawDescGZIP(), []int{1}
}

func (x *BlockedPlayer) GetAccountId() *protocol.EntityId {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *BlockedPlayer) GetBattleTag() string {
	if x != nil && x.BattleTag != nil {
		return *x.BattleTag
	}
	return ""
}

// Deprecated: Marked as deprecated in bgs/low/pb/client/user_manager_types.proto.
func (x *BlockedPlayer) GetRole() []uint32 {
	if x != nil {
		return x.Role
	}
	return nil
}

// Deprecated: Marked as deprecated in bgs/low/pb/client/user_manager_types.proto.
func (x *BlockedPlayer) GetPrivileges() uint64 {
	if x != nil && x.Privileges != nil {
		return *x.Privileges
	}
	return 0
}

var File_bgs_low_pb_client_user_manager_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_user_manager_types_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x62, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x37, 0x62, 0x67, 0x73, 0x2f,
	0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x27, 0x62, 0x67, 0x73, 0x2f, 0x6c,
	0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x61, 0x6d, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x12, 0x37, 0x0a,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x07, 0x3a, 0x01, 0x30, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x67, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02, 0x18, 0x01, 0x52, 0x0a, 0x70, 0x72, 0x69,
	0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x63, 0x72, 0x61, 0x66,
	0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x62,
	0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x50, 0x00,
}

var (
	file_bgs_low_pb_client_user_manager_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_user_manager_types_proto_rawDescData = file_bgs_low_pb_client_user_manager_types_proto_rawDesc
)

func file_bgs_low_pb_client_user_manager_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_user_manager_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_user_manager_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_user_manager_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_user_manager_types_proto_rawDescData
}

var file_bgs_low_pb_client_user_manager_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bgs_low_pb_client_user_manager_types_proto_goTypes = []interface{}{
	(*RecentPlayer)(nil),       // 0: bgs.protocol.user_manager.v1.RecentPlayer
	(*BlockedPlayer)(nil),      // 1: bgs.protocol.user_manager.v1.BlockedPlayer
	(*protocol.EntityId)(nil),  // 2: bgs.protocol.EntityId
	(*protocol.Attribute)(nil), // 3: bgs.protocol.Attribute
}
var file_bgs_low_pb_client_user_manager_types_proto_depIdxs = []int32{
	2, // 0: bgs.protocol.user_manager.v1.RecentPlayer.entity_id:type_name -> bgs.protocol.EntityId
	3, // 1: bgs.protocol.user_manager.v1.RecentPlayer.attributes:type_name -> bgs.protocol.Attribute
	2, // 2: bgs.protocol.user_manager.v1.BlockedPlayer.account_id:type_name -> bgs.protocol.EntityId
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_user_manager_types_proto_init() }
func file_bgs_low_pb_client_user_manager_types_proto_init() {
	if File_bgs_low_pb_client_user_manager_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_user_manager_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecentPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_user_manager_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockedPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_user_manager_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_user_manager_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_user_manager_types_proto_depIdxs,
		MessageInfos:      file_bgs_low_pb_client_user_manager_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_user_manager_types_proto = out.File
	file_bgs_low_pb_client_user_manager_types_proto_rawDesc = nil
	file_bgs_low_pb_client_user_manager_types_proto_goTypes = nil
	file_bgs_low_pb_client_user_manager_types_proto_depIdxs = nil
}
