// DO NOT EDIT: this file was auto-generated by Gophercraft/protoss

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: bgs/low/pb/client/game_utilities_types.proto

package v1

import (
	protocol "github.com/Gophercraft/core/bnet/pb/bgs/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerVariables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity  *protocol.Identity    `protobuf:"bytes,1,req,name=identity" json:"identity,omitempty"`
	Rating    *float64              `protobuf:"fixed64,2,opt,name=rating" json:"rating,omitempty"`
	Attribute []*protocol.Attribute `protobuf:"bytes,3,rep,name=attribute" json:"attribute,omitempty"`
}

func (x *PlayerVariables) Reset() {
	*x = PlayerVariables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerVariables) ProtoMessage() {}

func (x *PlayerVariables) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerVariables.ProtoReflect.Descriptor instead.
func (*PlayerVariables) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_game_utilities_types_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerVariables) GetIdentity() *protocol.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *PlayerVariables) GetRating() float64 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *PlayerVariables) GetAttribute() []*protocol.Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAddress     *string `protobuf:"bytes,1,opt,name=client_address,json=clientAddress" json:"client_address,omitempty"`
	PrivilegedNetwork *bool   `protobuf:"varint,2,opt,name=privileged_network,json=privilegedNetwork" json:"privileged_network,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_bgs_low_pb_client_game_utilities_types_proto_rawDescGZIP(), []int{1}
}

func (x *ClientInfo) GetClientAddress() string {
	if x != nil && x.ClientAddress != nil {
		return *x.ClientAddress
	}
	return ""
}

func (x *ClientInfo) GetPrivilegedNetwork() bool {
	if x != nil && x.PrivilegedNetwork != nil {
		return *x.PrivilegedNetwork
	}
	return false
}

var File_bgs_low_pb_client_game_utilities_types_proto protoreflect.FileDescriptor

var file_bgs_low_pb_client_game_utilities_types_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e,
	0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x27,
	0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x2f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x62, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x62,
	0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x77, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x94, 0x01, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x35, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x62, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x12,
	0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x64, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c,
	0x65, 0x67, 0x65, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x44, 0x5a, 0x42, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72,
	0x63, 0x72, 0x61, 0x66, 0x74, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x62, 0x6e, 0x65, 0x74, 0x2f,
	0x70, 0x62, 0x2f, 0x62, 0x67, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x76,
	0x31,
}

var (
	file_bgs_low_pb_client_game_utilities_types_proto_rawDescOnce sync.Once
	file_bgs_low_pb_client_game_utilities_types_proto_rawDescData = file_bgs_low_pb_client_game_utilities_types_proto_rawDesc
)

func file_bgs_low_pb_client_game_utilities_types_proto_rawDescGZIP() []byte {
	file_bgs_low_pb_client_game_utilities_types_proto_rawDescOnce.Do(func() {
		file_bgs_low_pb_client_game_utilities_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_bgs_low_pb_client_game_utilities_types_proto_rawDescData)
	})
	return file_bgs_low_pb_client_game_utilities_types_proto_rawDescData
}

var file_bgs_low_pb_client_game_utilities_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bgs_low_pb_client_game_utilities_types_proto_goTypes = []interface{}{
	(*PlayerVariables)(nil),    // 0: bgs.protocol.game_utilities.v1.PlayerVariables
	(*ClientInfo)(nil),         // 1: bgs.protocol.game_utilities.v1.ClientInfo
	(*protocol.Identity)(nil),  // 2: bgs.protocol.Identity
	(*protocol.Attribute)(nil), // 3: bgs.protocol.Attribute
}
var file_bgs_low_pb_client_game_utilities_types_proto_depIdxs = []int32{
	2, // 0: bgs.protocol.game_utilities.v1.PlayerVariables.identity:type_name -> bgs.protocol.Identity
	3, // 1: bgs.protocol.game_utilities.v1.PlayerVariables.attribute:type_name -> bgs.protocol.Attribute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bgs_low_pb_client_game_utilities_types_proto_init() }
func file_bgs_low_pb_client_game_utilities_types_proto_init() {
	if File_bgs_low_pb_client_game_utilities_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerVariables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bgs_low_pb_client_game_utilities_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bgs_low_pb_client_game_utilities_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bgs_low_pb_client_game_utilities_types_proto_goTypes,
		DependencyIndexes: file_bgs_low_pb_client_game_utilities_types_proto_depIdxs,
		MessageInfos:      file_bgs_low_pb_client_game_utilities_types_proto_msgTypes,
	}.Build()
	File_bgs_low_pb_client_game_utilities_types_proto = out.File
	file_bgs_low_pb_client_game_utilities_types_proto_rawDesc = nil
	file_bgs_low_pb_client_game_utilities_types_proto_goTypes = nil
	file_bgs_low_pb_client_game_utilities_types_proto_depIdxs = nil
}
