package autocode

import (
	"fmt"
	"os"
	"path/filepath"
)

type Printer struct {
	File *os.File
}

func (g *Generator) NewPrinter(path string) (p *Printer, err error) {
	p = new(Printer)

	if err = g.ensurePath(path); err != nil {
		return
	}

	p.File, err = os.OpenFile(
		filepath.Join(g.Dir, path),
		os.O_CREATE|os.O_RDWR|os.O_TRUNC,
		0700,
	)

	if err != nil {
		return
	}

	p.Printf("// DO NOT EDIT: generated by whoa_autocode\n")
	return
}

func (p *Printer) Printf(format string, args ...any) {
	fmt.Fprintf(p.File, format, args...)
}

func (p *Printer) Close() error {
	return p.File.Close()
}
